name: $(Date:yyyy).1$(DayOfYear)$(Rev:.r).0

trigger: none

variables:
  BuildConfiguration: 'debug'

resources:
  containers:
    - container: msbuildcontainer
      image: isynergyonline/buildtools:18362

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
    - template: templates/build.jobs.yml
      parameters:
        BuildConfiguration: $(BuildConfiguration)