# File: pipelines/artifacts.jobs.yml

jobs:
- job: ArtifactsJob
  displayName: 'Process artifacts Pay.nl libraries'
  container: msbuildcontainer
  steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'Output'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: PowerShell@2
      displayName: 'PowerShell Script - Update buildnumber'
      inputs:
        targetType: filePath
        filePath: ./build/updatebuildnumber.ps1
        arguments: '-previousBuildNumber "$env:BUILD_BUILDNUMBER"'

    - task: NuGetToolInstaller@1
      displayName: 'Use NuGet 5.1.0'
      inputs:
        versionSpec: 5.1.0

    - task: NuGetCommand@2
      displayName: 'NuGet pack - Pay.nl'
      inputs:
        command: pack
        packagesToPack: 'nuget/Package.nuspec'
        buildProperties: 'Version=$(build.buildNumber);PackageVersion=$(build.buildNumber);AssemblyFolder=$(System.ArtifactsDirectory)\Output;BuildConfiguration=$(BuildConfiguration)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: Pay.nl'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\Pay.nl.$(build.buildNumber).nupkg'
        artifactName: Upload